twig:
    default_path: '%kernel.project_dir%/templates'

when@test:
# config/packages/twig.yaml
    twig:
        debug: '%kernel.debug%'
        strict_variables: '%kernel.debug%'
        form_themes: ['bootstrap_5_layout.html.twig'] # accepte plusieurs thèmes
